name: example-chrome
on:
  push:
    branches:
      - 'main'
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress.io
        uses: cypress-io/github-action@3
        with:
          start: npm run run:staging
        

      
