name: example-chrome
on:
  push:
    branches:
      - 'main'
 
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Cypress.io
        uses: cypress-io/github-action@2.9.7
        with:
          start: npm run run:staging
        

      
